### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException in ZoomHelper

### ISSUE THREAD

**Issue by PankajSavaliya** [Aghajari/ZoomHelper#3]
Fatal Exception: java.lang.NullPointerException
       at com.aghajari.zoomhelper.ZoomHelper$load$1.run(ZoomHelper.java:205)
       at -$$LambdaGroup$js$xzCUdXiP0Q4TFHhL_Vv-FNKpLyA.run(-.java:3)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Aghajari** [comment]
Hi @PankajSavaliya ,
What is your code? Are you running my sample?

**Comment by PankajSavaliya** [comment]
I have implemented one of my app, just getting this type of crash log from firebase crashltyics. I have implemented this function as your sample code, nothing has changed from my side. I hope this Log will be helpful.

**Comment by Aghajari** [comment]
Hello again @PankajSavaliya ,
i've checked and i'm sure there is no bug in the lib,
you should check your code again! OR attach a simple project and i'll check it

**Comment by dhivya29** [comment]
Hi @Aghajari  from zoomHelper 
if (placeHolderEnabled) {
                    view.postDelayed(Runnable {
                        placeHolderView!!.visibility = View.INVISIBLE
                    }, placeHolderDelay)
                }  this not null !! is getting crash i think can you please check and update the code
